import{a as S,S as w,i as l}from"./assets/vendor-C24jorn_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const x="49078032-cb7d53c2015160b8e7ee9b72b",E="https://pixabay.com/api/";async function u(o,t=1,a=40){try{return(await S.get(E,{params:{key:x,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a}})).data}catch(s){throw console.error("Error",s),s}}function g(o,t=!1){const a=document.querySelector(".gallery"),s=o.map(({webformatURL:r,largeImageURL:n,tags:p,likes:f,views:h,comments:b,downloads:L})=>`
<li class="gallery-item">
    <a href="${n}">
        <img src="${r}" alt="${p}" loading="lazy" />
    </a>
    <div class="info">
        <p data-label="Likes">${f}</p>
        <p data-label="Views">${h}</p>
        <p data-label="Comments">${b}</p>
        <p data-label="Downloads">${L}</p>
    </div>
</li>
`).join("");t?a.insertAdjacentHTML("beforeend",s):a.innerHTML=s,new w(".gallery a").refresh()}const q=document.querySelector(".search-form"),v=document.querySelector(".gallery"),y=document.querySelector(".load-more"),i=document.querySelector(".loading-message");let c=1,d="",m=0;q.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.target.elements.searchQuery.value.trim(),c=1,v.innerHTML="",y.style.display="none",i.style.display="block",!d){l.error({message:"Sorry, there are no images matching your search query. Please, try again!",messageColor:"#fafafb",color:"#EF4040",position:"topRight",maxWidth:"432px"}),i.style.display="none";return}try{const t=await u(d,c);if(i.style.display="none",!t.hits.length){l.warning({message:"Sorry, there are no images matching your search query. Please, try again!",messageColor:"#fafafb",color:"#EF4040",position:"topRight",maxWidth:"432px"});return}m=t.totalHits,g(t.hits),m>40&&(y.style.display="block")}catch{l.error({message:"Error fetching images"}),i.style.display="none"}});y.addEventListener("click",async()=>{c+=1,i.style.display="block";try{const o=await u(d,c);g(o.hits,!0),i.style.display="none",c*40>=m&&(y.style.display="none",l.info({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fafafb",color:"#EF4040",position:"topRight",maxWidth:"432px"}));const{height:a}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}catch{l.error({message:"Error fetching more images"}),i.style.display="none"}});
//# sourceMappingURL=index.js.map
