import{a as w,S as L,i}from"./assets/vendor-C24jorn_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const S="49078032-cb7d53c2015160b8e7ee9b72b",v="https://pixabay.com/api/";async function y(o,t=1,a=40){try{return(await w.get(v,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a}})).data}catch(s){throw console.error("Error",s),s}}function p(o,t=!1){const a=document.querySelector(".gallery"),s=o.map(({webformatURL:r,largeImageURL:l,tags:f,likes:g,views:m,comments:h,downloads:b})=>`
<li class="gallery-item">
    <a href="${l}">
        <img src="${r}" alt="${f}" loading="lazy" />
    </a>
    <div class="info">
        <p data-label="Likes">${g}</p>
        <p data-label="Views">${m}</p>
        <p data-label="Comments">${h}</p>
        <p data-label="Downloads">${b}</p>
    </div>
</li>
`).join("");t?a.insertAdjacentHTML("beforeend",s):a.innerHTML=s,new L(".gallery a").refresh()}const q=document.querySelector(".search-form"),x=document.querySelector(".gallery"),c=document.querySelector(".load-more"),n=document.querySelector(".loading-message");let u=1,d="";q.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.target.elements.searchQuery.value.trim(),u=1,x.innerHTML="",c.style.display="none",n.style.display="block",!d){i.error({message:"Enter a search query!",messageColor:"#fafafb",color:"#EF4040",position:"topRight",maxWidth:"432px"}),n.style.display="none";return}try{const t=await y(d,u);if(n.style.display="none",!t.hits.length){i.warning({message:"No images found. Try another search!",messageColor:"#fafafb",color:"#EF4040",position:"topRight",maxWidth:"432px"});return}p(t.hits),t.hits.length===40&&(c.style.display="block")}catch{i.error({message:"Something went wrong!"}),n.style.display="none"}});c.addEventListener("click",async()=>{u+=1,n.style.display="block";try{const o=await y(d,u);if(n.style.display="none",!o.hits.length){c.style.display="none",i.info({message:"You've reached the end of search results."});return}p(o.hits,!0),o.hits.length<40&&(c.style.display="none",i.info({message:"You've reached the end of search results."}));const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{i.error({message:"Something went wrong!"}),n.style.display="none"}});
//# sourceMappingURL=index.js.map
